### ISSUE TITLE
zPermissions Related vvv

### ISSUE THREAD

**Issue by mishyy** [ZerothAngel/ToHPluginUtils#3]
Hello @ZerothAngel ,
Sorry for coming over here to bother you about zpermissions, but it appears you have disabled issues on it, and you are no longer active on BukkitDev, so I have had to resort to coming here.

I was recently interested in editing the code of zPermissions, more specifically the messages, but to disarray, when i cloned the repository i was met with nothing but errors due to the dependencies in the pom not working, as the links no longer work etc.

So I was wondering if you could take some time out of your busy day and update the dependencies so that myself along with I'm sure a few other developers may continue to easily contribute to your wonderful project.

Regards,
Mitchell || xMItchIDE

**Comment by ZerothAngel** [comment]
I really haven't kept up on Minecraft/Bukkit things since the DMCA takedown a few years ago. And I don't play Minecraft anymore.

Anything of mine that was available on my own server (maven.tyrannyofheaven.org) should still be available here, at least in source form.

All the other Bukkit-related dependencies are with other people/groups. (I'm assuming the other, more common dependencies such as h2 are still available at Maven Central.)

So you, or someone else familiar with the current landscape of Bukkit plugins, would know how to update the dependencies better than I.

For the most part, I believe I wrote it modular enough to easily rip out those dependencies, if need be &mdash; see the region and vault packages.

**Comment by mishyy** [comment]
The maven.tyrannyofheaven.org site is currently down, along with your jenkins/ci server.
